application/auth.py
from flask import Blueprint, redirect, render_template, flash, request, session, url_for
from flask_login import login_required, logout_user, current_user, login_user
from .forms import LoginForm, SignupForm, RequestResetForm, ResetPasswordForm
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, mail
from .models import User
from flask_mail import Message

auth_bp = Blueprint('auth_bp', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user_check = db.session.query(User).filter(User.email==form.email.data).first()
        if user_check:
            if check_password_hash(user_check.password, form.password.data):
                login_user(user_check, remember=True)
                flash("Login Successful!")
                return redirect(url_for('views.home'))
            else:
                flash('Login Unsuccessful. Please check email and password.')

        if "next" in session and session["next"]:
            return redirect(session["next"])
    session["next"] = request.args.get("next")
    return render_template("login.html", form=form)

@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created!')
        return redirect(url_for('auth_bp.login'))
    return render_template("signup.html", form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_bp.login'))

def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message("Password Reset Request", sender="noreply@demo.com", recipients=[user.email])
    msg.body = f"""To reset your password visit following link: {url_for('auth_bp.reset_token', token=token, _external=True)}
    If you didn't make this request then ignore this email."""
    mail.send(msg)

@auth_bp.route('/reset_password', methods=["POST", "GET"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent with instructions.", "info")
        redirect(url_for("auth_bp.login"))
    return render_template("reset_request.html", form=form, title="Reset Password")

@auth_bp.route('/reset_password/<token>', methods=["POST", "GET"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for('auth_bp.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been update! You are now able to log in!')
        return redirect(url_for('auth_bp.login'))
    return render_template("reset_token.html", form=form, title="Reset Password")

application/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_required, current_user
from .forms import UpdateAccountForm
from . import db, app
import secrets
import os, json
from PIL import Image
import yfinance as yf
from .models import StockItem, Stock
from datetime import datetime
import numpy as np

views = Blueprint('views', __name__)

datetime_dict = {}

@views.route('/', methods=["POST", "GET"])
@login_required
def home():
    context = {
        "stocks": db.session.query(Stock).all(),
        "last_enter": datetime_dict
    }
    return render_template("home.html", user=current_user, context=context)

stock_tickers = ("AAPL", "TSLA", "TWTR", "NVDA", "AMZN", "NFLX")

def load_data(symbol, interval, start, end):
    ticker = yf.Ticker(symbol)
    dataframe = ticker.history(interval=interval, start=start, end=end, actions=False, rounding=True)
    stock = get_or_create_stock(symbol)

    for data in dataframe.index:
        date_string = data.strftime("%Y-%m-%d %H:%M")
        open = dataframe.iloc[:, 0][data]
        high = dataframe.iloc[:, 1][data]
        low = dataframe.iloc[:, 2][data]
        close = dataframe.iloc[:, 3][data]
        volume = dataframe.iloc[:, 4][data]
        stock_open = StockItem(stock_date=date_string, stock_open=open, stock_high=high, stock_low=low, stock_close=close, stock_volume=volume, stock=stock)
        db.session.add(stock_open)
        db.session.commit()

def get_or_create_stock(symbol):
    ticker = yf.Ticker(symbol)
    stock = db.session.query(Stock).filter(Stock.stock_name == symbol).first()
    if not stock:
        long_name = ticker.info.get("longName")
        business_summary = ticker.info.get("longBusinessSummary")
        website = ticker.info.get("website")
        market_cap = ticker.fast_info.get("market_cap")
        open_price = ticker.fast_info.get("open")
        previous_close = ticker.fast_info.get("previous_close")
        currency = ticker.fast_info.get("currency")
        stock_open = Stock(stock_name=symbol, long_name=long_name, business_summary=business_summary, website=website, market_cap=market_cap, open_price=open_price, previous_close=previous_close, currency=currency)
        db.session.add(stock_open)
        db.session.commit()
        return db.session.query(Stock).filter(Stock.stock_name == symbol).first()
    return stock

load_data("TSLA", "1d", "2022-12-01", "2023-01-23")

def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(app.root_path, 'static/profile_photos', picture_fn)
    output_size = (500, 500)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)
    return picture_fn

@views.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!")
        return redirect(url_for('views.account'))
    else:
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_photos/' + current_user.image_file)
    return render_template("account.html", title="Account", form=form, image_file=image_file)

def simple_moving_average(values, window):
    weights = np.repeat(1.0, window)/window
    smas = np.convolve(values, weights, 'valid')
    return list(smas)

@views.route("/tables/<symbol>")
@login_required
def tables(symbol):
    date_enter = datetime.now()
    format_date = datetime.strftime(date_enter, "%Y-%m-%d %H:%M:%S")
    datetime_dict[symbol] = format_date

    page = request.args.get('page', 1, type=int)
    stock = db.session.query(Stock).filter(Stock.stock_name == symbol).first()
    items = db.session.query(StockItem).filter(StockItem.stock_id == stock.id).paginate(page=page, per_page=20)

    dates, lowes, highs, opens, closes = stock.get_data()
    sma = simple_moving_average(closes, 5)
    context = {
        "stock": stock,
        "stock_items": items,
        "dates": json.dumps(dates),
        "lowes": json.dumps(lowes),
        "highs": json.dumps(highs),
        "opens": json.dumps(opens),
        "closes": json.dumps(closes),
        "page": page,
        "sma": sma
    }
    return render_template("tables.html", context=context, items=items)

application/templates/account.html
{% extends "layout.html" %}
{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-primary" role="alert">
                {{ message }}
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}
<div class="col-4 offset-4 my-5">
    <div class="card">
        <div class="card-body">
            <div class="content-section">
                <div class="media" >
                  <img class="rounded-circle card-img-top" src="{{ image_file }}" sizes="">
                  <div class="card-body text-center">
                    <h4 class="account-heading">{{ current_user.username }}</h4>
                      <p class="text-secondary">{{ current_user.email }}</p>
                  </div>
                </div>
                <form method="POST" action="{{ url_for('views.account') }}" enctype="multipart/form-data" novalidate>
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Account info</legend>
                        <div class="form-group">
                            {{ form.username.label(class="form-control-label") }}
                            {% if form.username.errors %}
                                {{ form.username(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.username(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group mb-3">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group mb-3">
                            {{ form.picture.label() }}<br>
                            {{ form.picture(class="form-control-file") }}<br>
                            {% if form.picture.errors %}
                                {% for error in form.picture.errors %}
                                    <span class="text-danger">{{ error }}</span><br>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group mb-3">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

application/templates/home.html
{% extends "layout.html" %}
{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-primary" role="alert">
                {{ message }}
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}
<div class="col-8 offset-2 my-5">
    <div class="card">
        <div class="card-body">
            <p class="lead text-center">STOCKS</p>
              <div class="mb-3">
                <div class="list-group">
                  {% for stock in context.stocks %}
                  <a href="{{ url_for('views.tables', symbol=stock.stock_name, page='1') }}" class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                      <h5 class="mb-1">{{ stock.stock_name }} </h5>
                        {% for symbol, date in context.last_enter.items() %}
                        {% if symbol ==  stock.stock_name %}
                            <small> Last entry: {{ date }}</small>
                        {% endif %}
                        {% endfor %}
                    </div>
                    <p class="mb-1">{{ stock.long_name }}</p>
                    <small>{{ stock.website }}</small>
                  </a>
                  {% endfor %}
                </div>
              </div>
        </div>
    </div>
</div>
{% endblock %}

application/templates/layout.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="description" content={{description}}>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/favicon.ico">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    {% block title %}
    <title></title>
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.plot.ly/plotly-2.16.1.min.js"></script>
  </head>
  <body>
     {% include 'navigation.html' %}
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

application/templates/login.html
{% extends "layout.html" %}
{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-primary" role="alert">
                {{ message }}
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}
<div class="col-8 offset-2 my-5">
    <div class="card">
        <div class="card-body">
            <div class="content-section">
                <form method="POST" action="{{ url_for('auth_bp.login') }}" novalidate>
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4 text-center">Log In</legend>
                        <div class="form-group">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.password.label(class="form-control-label") }}
                            {% if form.password.errors %}
                                {{ form.password(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-check mb-3">
                            {{ form.remember(class="form-check-input") }}
                            {{ form.remember.label(class="form-check-label") }}
                        </div>
                    </fieldset>
                    <div class="form-group mb-3">
                        {{ form.submit(class="btn btn-outline-info") }}
                        <small class="text-muted ml-2">
                        <a href="{{ url_for('auth_bp.reset_request')}}">Forgot Password?</a>
                    </small>
                    </div>
                </form>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Need An Account? <a class="ml-2" href="{{ url_for('auth_bp.signup') }}">Sign Up Now</a>
                </small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

application/templates/navigation.html
<header>
<nav class="navbar navbar-expand-lg bg-light position-sticky top-0">
  <div class="container">
    <a class="navbar-brand" href="{{ url_for('views.home') }}">StockView</a>
      <ul class="nav justify-content-end">
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('views.account') }}">Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth_bp.logout') }}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{{ url_for('auth_bp.login') }}">Login</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('auth_bp.signup') }}">Sign up</a>
        </li>
        {% endif %}
      </ul>
  </div>
</nav>
</header>

application/templates/signup.html
{% extends "layout.html" %}
{% block content %}
<div class="col-8 offset-2 my-5">
    <div class="card">
        <div class="card-body">
            <div class="content-section">
                <form method="POST" action="{{ url_for('auth_bp.signup') }}" novalidate>
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4 text-center">Join Today</legend>
                        <div class="form-group">
                            {{ form.username.label(class="form-control-label") }}
                            {% if form.username.errors %}
                                {{ form.username(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.username(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.email.label(class="form-control-label") }}

                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.password.label(class="form-control-label") }}

                            {% if form.password.errors %}
                                {{ form.password(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group mb-3">
                            {{ form.confirm_password.label(class="form-control-label") }}

                            {% if form.confirm_password.errors %}
                                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.confirm_password.errors %}
                                        <span> {{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.confirm_password(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group mb-3">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Already Have an Account? <a class="ml-2" href="{{ url_for('auth_bp.login') }}">Sign in</a>
                </small>
            </div>
        </div>
    </div>
</div>
{% endblock %}

application/templates/tables.html
{% extends "layout.html" %}
{% block content %}
<div class="col-8 offset-2 my-5">
    <div class="card">
        <div class="card-body">
            <h5 class="lead text-center">Chart</h5>
            <hr>
            <div id="myDiv"></div>
            <div>
              <hr>
              <h5 class="lead text-center mb-4">About company</h5>
              <div class="accordion mb-3" id="accordionExample">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                      Full Name
                    </button>
                  </h2>
                  <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                      <strong>{{ context.stock.long_name }}</strong>
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      Business Summary
                    </button>
                  </h2>
                  <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <p>{{ context.stock.business_summary }}</p>
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingThree">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                      Website
                    </button>
                  </h2>
                  <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                      <a href=" {{ context.stock.website }}">{{ context.stock.website }}</a>
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingFive">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                      Market Cap
                    </button>
                  </h2>
                  <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                      <p>{{ context.stock.market_cap }}B</p>
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingSeven">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
                      Open Price
                    </button>
                  </h2>
                  <div id="collapseSeven" class="accordion-collapse collapse" aria-labelledby="headingSeven" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                      <p>{{ context.stock.open_price }}</p>
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingEight">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
                      Previous Close
                    </button>
                  </h2>
                  <div id="collapseEight" class="accordion-collapse collapse" aria-labelledby="headingEight" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                      <p>{{ context.stock.previous_close }}</p>
                    </div>
                  </div>
                </div>
                <div class="accordion-item">
                  <h2 class="accordion-header" id="headingNine">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseNine" aria-expanded="false" aria-controls="collapseNine">
                      Currency
                    </button>
                  </h2>
                  <div id="collapseNine" class="accordion-collapse collapse" aria-labelledby="headingNine" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                      <p>{{ context.stock.currency }}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div>
              <hr>
              <h5 class="lead text-center mb-4">Table</h5>
              <table id="example" class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th scope="col">Date</th>
                  <th scope="col">Open</th>
                  <th scope="col">High</th>
                  <th scope="col">Low</th>
                  <th scope="col">Close</th>
                  <th scope="col">Volume</th>
                </tr>
              </thead>
              <tbody>
              {% for post in context.stock_items.items %}
                <tr>
                  <td>{{ post.stock_date }}</td>
                  <td>{{ post.stock_open }}</td>
                  <td>{{ post.stock_high }}</td>
                  <td>{{ post.stock_low }}</td>
                  <td>{{ post.stock_close }}</td>
                  <td>{{ post.stock_volume }}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
              {% for page_num in context.stock_items.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                  {% if context.stock_items.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('views.tables', symbol=context.stock.stock_name, page=page_num) }}">{{ page_num }}</a>
                  {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('views.tables', symbol=context.stock.stock_name, page=page_num) }}">{{ page_num }}</a>
                  {% endif %}
                {% else %}
                  ...
                {% endif %}
              {% endfor %}
            </div>
        </div>
    </div>
</div>
<script>
var trace1 = {

  x: {{ context.dates|safe }},

  close: {{ context.closes|safe }},

  decreasing: {line: {color: 'red'}},

  high: {{ context.highs|safe }},

  increasing: {line: {color: 'black'}},

  line: {color: 'rgba(31,119,180,1)'},

  low: {{ context.lowes|safe }},

  open: {{ context.opens|safe }},

  type: 'candlestick',
  xaxis: 'x',
  yaxis: 'y',
  name: 'Bars',
};

var trace2 = {
  x: {{ context.dates|safe }},
  y: {{ context.sma|safe }},
  type: 'scatter',
  mode: 'lines',
  name: 'SMA (5)',
};

var data = [trace1, trace2];

var layout = {
  dragmode: 'zoom',
  margin: {
    r: 10,
    t: 25,
    b: 40,
    l: 60
  },
  showlegend: true,
  xaxis: {
    autorange: true,
    range: [{{ context.dates[0]|safe }}, {{ context.dates[-1]|safe }}],
    rangeslider: {range: [{{ context.dates[0]|safe }}, {{ context.dates[-1]|safe }}]},
    title: 'Date',
    type: 'date',
    rangeselector: {
        x: 0,
        y: 1.2,
        xanchor: 'left',
        font: {size:8},
        buttons: [{
            step: 'month',
            stepmode: 'backward',
            count: 1,
            label: '1 month'
        }, {
            step: 'month',
            stepmode: 'backward',
            count: 6,
            label: '6 months'
        }, {
            step: 'all',
            label: 'All dates'
        }]
    },
  },
  yaxis: {
    autorange: true,
    type: 'linear',
    title: 'Price',
  },
};
Plotly.newPlot('myDiv', data, layout);
</script>
{% endblock %}